#! /bin/bash

echo "resetting..."
rm -f resources/*
cp originalTest/* resources/

echo "running..."
cd resources
../../bin/comp numPartitions=3 insertionSort=false alterSchedule=false memBudget=4 inputGraph=../preproc/bigtest.txt grammar=grammar
PID=$( echo $( ps -f  | grep "../../bin/comp" | awk '{print $2}' ) | awk '{print $1}' )

../pmap.sh $PID > pmap.output.$1 &

