#! /bin/bash

echo "resetting..."
rm -f resources/*
cp originalTest/* resources/

echo "running..."
cd resources
nohup ../../bin/comp memBudget=$1 > cpp.output.$1 &
PID=$( echo $( ps -f  | grep "../../bin/comp" | awk '{print $2}' ) | awk '{print $1}' )

nohup ./pmap.sh $PID > pmap.output.$1

